### ISSUE TITLE
Edit Seasons and manual add

### ISSUE THREAD

**Issue by davepatt** [toroettg/SeriesMarker#2]
Hi i find your program very interesting , but i want to edit seasons to remove some episodes (like specials which i dont own all ) and add entry manual for series which dont have info

Thank you very much for implementing this features in future releases

**Comment by toroettg** [comment]
Hello,

I have not planned to implement functionality for adding 'custom' episodes/series. However,
if you find that a series is missing, you can visit http://www.thetvdb.com and add it directly to their database. SeriesMarker is currently able to fetch information for entries in English, only. I am aware this excludes some series with non-English-speaking origin and language support is planned for some future release.

The removal of episodes is also not planned right now, but I could imagine a way for hiding them in some distant future release. This tends towards filtering mechanics, which could add a degree of complexity to the user interface, that I like to avoid. I will keep it in mind.

Since I also think that series specials are to be handled more like nice to have items, the next release will bring a user-option to exclude them from progress counting. I am currently laying the foundations for this, as my time allows. 

Your title suggests that adding/removing episodes are the features that you are primarily requesting with this ticket. I hope it is not too rash, but I guess it should be closed as those are out of project scope at the moment.

Thank you for your feedback!

Kind regards,
Tobias
